from __future__ import annotations

from dataclasses import asdict
import json
import re
import unicodedata
import time
from datetime import date, datetime, time as dtime
from abc import ABC, abstractmethod
from typing import Any
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError

from .settings import AppSettings
from .contracts import PlannerAction, QueryResult, SchemaMetadata, TableMetadata


# =========================================================
# ABSTRACT
# =========================================================
class QueryPlanner(ABC):
    @abstractmethod
    def build_action(
        self,
        prompt: str,
        schema_metadata: dict[str, SchemaMetadata],
        previous_queries: list[str] | None = None,
        previous_results: list[QueryResult] | None = None,
        assistant_history: list[str] | None = None,
        sample_data: list[dict] | None = None,
    ) -> PlannerAction:
        raise NotImplementedError


# =========================================================
# FALLBACK
# =========================================================
class HeuristicQueryPlanner(QueryPlanner):
    def build_action(
        self,
        prompt,
        schema_metadata,
        previous_queries=None,
        previous_results=None,
        assistant_history=None,
        sample_data=None,
    ) -> PlannerAction:
        print("[Heuristic] fallback activated")
        first_schema = next(iter(schema_metadata.values()))
        table = first_schema.tables[0].name
        return PlannerAction(
            action="execute",
            sql=[f"SELECT * FROM {table} LIMIT 10;"],
            dataset_id=first_schema.database_id,
            comment="Fallback query generated by heuristic planner.",
        )


# =========================================================
# OLLAMA PLANNER
# =========================================================
class OllamaQueryPlanner(QueryPlanner):

    def __init__(self, settings: AppSettings, fallback_planner=None):
        self._settings = settings
        self._fallback = fallback_planner or HeuristicQueryPlanner()

    def build_action(
        self,
        prompt,
        schema_metadata,
        previous_queries=None,
        previous_results=None,
        assistant_history=None,
        sample_data: list[dict] | None = None,
    ) -> PlannerAction:

        print("\n================ OLLAMA PLANNER ================")
        print("[Planner] prompt:", prompt)
        print("[Planner] datasets:", list(schema_metadata.keys()))

        print("[Planner] model:", self._settings.ollama_model)
        print("[Planner] base_url:", self._settings.ollama_base_url)

        print("[Planner] previous_queries:", previous_queries)
        print("[Planner] previous_results:", len(previous_results) if previous_results else 0)
        print("[Planner] assistant_history:", assistant_history)

        t0 = time.time()

        try:
            action = self._call_ollama(
                prompt,
                schema_metadata,
                previous_queries,
                previous_results,
                assistant_history,
                sample_data,
            )
            print("[Planner] TOTAL TIME:", round(time.time() - t0, 2), "s")

            return action

        except Exception as e:
            print("\n[Planner] ERROR:", repr(e))
            print("[Planner] fallback triggered\n")
            return self._fallback.build_action(
                prompt,
                schema_metadata,
                previous_queries=previous_queries,
                previous_results=previous_results,
                assistant_history=assistant_history,
                sample_data=sample_data,
            )

    def _call_ollama(
        self,
        prompt,
        schema_metadata,
        previous_queries,
        previous_results,
        assistant_history,
        sample_data=None,
    ) -> PlannerAction:

        print("\n[Planner] CALLING OLLAMA...")

        schema_descriptions = []
        for dataset_id, schema in schema_metadata.items():
            schema_descriptions.append(self._build_schema_summary(dataset_id, schema))

        schema_str = "\n\n".join(schema_descriptions)

        print("[Planner] SCHEMA OVERVIEW SIZE:", len(schema_str))
        print("[Planner] SCHEMA OVERVIEW:\n", schema_str)
        print("[Planner] SAMPLE DATA:", sample_data)
        print("[Planner] ASSISTANT HISTORY:\n", assistant_history[-6:] if assistant_history else [])

        final_prompt = f"""
        You are a Data Understanding and SQL Assistant.

        Your job is to analyze the user request and the dataset structure, then create a compact work plan and execute queries if needed.

        ---

        USER TASK:
        {prompt}

        ---

        AVAILABLE DATASETS:
        {schema_str}

        ---

        PREVIOUS QUERIES:
        {json.dumps(previous_queries or [], ensure_ascii=False, indent=2)}

        PREVIOUS RESULTS SUMMARY:
        {json.dumps([{{'row_count': len(r.rows), 'truncated': r.truncated}} for r in (previous_results or [])], ensure_ascii=False, indent=2)}

        ASSISTANT HISTORY:
        {json.dumps((assistant_history or [])[-6:], ensure_ascii=False, indent=2)}

        ---

        RESPONSE FORMAT:
        Return a JSON object only. The JSON object must include:
        - action: "plan", "execute", "analysis", or "final"
        - intent: a short identifier for the reasoning intent
        - sql: a list of SQL statements when action == "execute"
        - dataset_id: the dataset to run the SQL against, if needed
        - plan_steps: a list of structured plan steps when action == "plan"
        - comment: a short explanation of the plan or analysis
        - metadata: optional extra details

        Example responses:
        {{"action":"plan","intent":"data_quality_review","plan_steps":[{{"step_id":1,"dataset_id":"db1","description":"Count rows and nulls","sql":["SELECT COUNT(*) FROM table1;" ]}}],"comment":"Plan de trabajo inicial."}}
        {{"action":"execute","intent":"preview","dataset_id":"db1","sql":["SELECT * FROM table1 LIMIT 10;"],"comment":"Visualizar las primeras filas."}}
        {{"action":"analysis","intent":"schema_inspection","comment":"La tabla tiene 56 columnas y no hay claves primarias."}}
        {{"action":"final","intent":"conclusion","comment":"El análisis de calidad se completó."}}

        RULES:
        1. Prefer action "plan" for multi-step or multi-dataset workflows.
        2. Return only valid JSON. Do not include any extra prose.
        3. If you need more data from prior results, use "action":"plan" and describe the next queries.
        4. If you want to execute SQL, return a list of statements in "sql" and specify "dataset_id" when multiple datasets are available.
        5. Use only available tables and columns; do not invent new schema names.
        6. If you are ready to complete, return "action":"final".
        """

        print("\n[Planner] FINAL PROMPT SIZE:", len(final_prompt))
        print("[Planner] --- PROMPT START ---")
        print(final_prompt[:500], "...")
        print("[Planner] --- PROMPT END ---")

        payload = json.dumps({
            "model": self._settings.ollama_model,
            "prompt": final_prompt,
            "stream": False,
        }).encode()

        print("\n[Planner] sending request to Ollama...")

        req = Request(
            f"{self._settings.ollama_base_url}/api/generate",
            data=payload,
            headers={"Content-Type": "application/json"},
        )

        start = time.time()

        try:
            with urlopen(req, timeout=self._settings.ollama_timeout_seconds) as r:
                print("[Planner] waiting response from Ollama...")
                raw = r.read().decode()

            print("[Planner] RAW RESPONSE SIZE:", len(raw))
            print("[Planner] RAW RESPONSE:", raw[:300])

            parsed = json.loads(raw)
            response = parsed.get("response", "").strip()

            print("[Planner] MODEL RESPONSE:", response)
            print("[Planner] OLLAMA TIME:", round(time.time() - start, 2), "s")

            # Try to parse response; if invalid, do a short re-ask loop
            max_reasks = 2
            parsed_action = self._parse_planner_response(response)
            if parsed_action.action in {"execute", "analysis", "plan", "final"} and (
                parsed_action.action != "execute" or parsed_action.sql
            ):
                return parsed_action

            # re-ask attempts with a compact correction prompt
            for retry in range(max_reasks):
                correction_prompt = f"""
                The previous response did not follow the required JSON schema.
                Respond ONLY with a valid JSON object.

                USER TASK:
                {prompt}

                AVAILABLE DATASETS:
                {schema_str}

                PREVIOUS QUERIES:
                {json.dumps(previous_queries or [], ensure_ascii=False, indent=2)}

                PREVIOUS RESULTS SUMMARY:
                {json.dumps([{{'row_count': len(r.rows), 'truncated': r.truncated}} for r in (previous_results or [])], ensure_ascii=False, indent=2)}

                ASSISTANT HISTORY:
                {json.dumps((assistant_history or [])[-6:], ensure_ascii=False, indent=2)}

                RESPONSE FORMAT:
                Return a JSON object only. The JSON object must include:
                - action: "plan", "execute", "analysis", or "final"
                - intent: a short identifier
                - sql: a list of SQL statements when action == "execute"
                - dataset_id: the dataset to target when multiple datasets are available
                - plan_steps: a list of steps when action == "plan"
                - comment: a short explanation
                - metadata: optional
                """

                payload = json.dumps({
                    "model": self._settings.ollama_model,
                    "prompt": correction_prompt,
                    "stream": False,
                }).encode()

                req = Request(
                    f"{self._settings.ollama_base_url}/api/generate",
                    data=payload,
                    headers={"Content-Type": "application/json"},
                )

                with urlopen(req, timeout=self._settings.ollama_timeout_seconds) as r:
                    raw2 = r.read().decode()

                parsed2 = json.loads(raw2)
                response2 = parsed2.get("response", "").strip()
                print(f"[Planner] Re-ask attempt {retry+1}, MODEL RESPONSE:", response2)
                parsed_action = self._parse_planner_response(response2)
                if parsed_action.action in {"execute", "analysis", "plan", "final"} and (
                    parsed_action.action != "execute" or parsed_action.sql
                ):
                    return parsed_action

            # If still invalid, return the last parse
            return parsed_action

        except (URLError, HTTPError, TimeoutError) as e:
            print("\n[Planner] OLLAMA ERROR:", repr(e))
            raise

    def _build_schema_summary(self, dataset_id: str, schema: SchemaMetadata) -> str:
        lines = [f"DATASET: {dataset_id}", f"DIALECT: {schema.dialect}", f"TABLES: {len(schema.tables)}"]
        for table in schema.tables:
            key_columns = ", ".join(table.primary_key) if table.primary_key else "none"
            column_count = len(table.columns)
            if column_count <= 12:
                column_names = ", ".join([col.name for col in table.columns])
            else:
                column_names = ", ".join([col.name for col in table.columns[:8]]) + ", ..."
            lines.append(f"- {table.name} ({column_count} cols, PK: {key_columns}): {column_names}")
        return "\n".join(lines)

    def simplify_schema(self, schema: dict) -> str:
        lines = []

        lines.append(f"DATABASE: {schema.get('database_id')}")
        lines.append(f"DIALECT: {schema.get('dialect')}")
        lines.append("")

        for table in schema.get("tables", []):
            lines.append(f"TABLE: {table.get('name')}")
            lines.append("")
            lines.append("COLUMNS:")

            for col in table.get("columns", []):
                name = col.get("name")
                col_type = col.get("type")

                flags = []

                if col.get("is_primary_key"):
                    flags.append("PK")

                if col.get("is_foreign_key"):
                    flags.append("FK")

                flag_str = f" [{', '.join(flags)}]" if flags else ""

                lines.append(f"- {name} ({col_type}){flag_str}")

            lines.append("")

            pk = table.get("primary_key", [])
            lines.append(f"PRIMARY KEY: {pk if pk else 'none'}")

            # relations (si existen)
            relations = table.get("relations", [])
            if relations:
                lines.append(f"RELATIONS: {relations}")
            else:
                lines.append("RELATIONS: none")

            lines.append(f"TOTAL COLUMNS: {len(table.get('columns', []))}")

        return "\n".join(lines)


    def _extract_sql(self, text: str) -> str:

        print("\n[_extract_sql] input:", text)

        text = text.strip()

        # 1. Detectar si es SQL con bloque de código
        match = re.search(r"```sql(.*?)```", text, re.S)
        if match:
            print("[_extract_sql] fenced SQL detected")
            sql = match.group(1).strip()
            if sql.lower().startswith(("select", "with")):
                return sql + ";"
            # Si el bloque SQL no empieza con SELECT/WITH, tratarlo como texto
            return sql

        # 2. Detectar si es SQL plano (sin bloques)
        if text.lower().startswith(("select", "with")):
            print("[_extract_sql] plain SQL detected")
            return text + ";"

        # 3. Detectar si es JSON (dataset evaluation)
        if text.startswith("{") and text.endswith("}"):
            print("[_extract_sql] JSON response detected, returning as-is")
            try:
                # Validar que sea JSON válido
                json.loads(text)
                return text
            except json.JSONDecodeError:
                print("[_extract_sql] invalid JSON, treating as plain text")
                return text

        # 4. Cualquier otra respuesta (texto plano, evaluación, etc.)
        print("[_extract_sql] plain text response, returning as-is")
        return text

    def _parse_planner_response(self, text: str) -> PlannerAction:

        print("[_parse_planner_response] input:", text)

        text = self._extract_json_payload(text)

        if text.startswith("{") and text.endswith("}"):
            try:
                payload = json.loads(text)
                action = payload.get("action")
                if action not in {"plan", "execute", "analysis", "final"}:
                    raise ValueError(f"Invalid action: {action}")

                intent = payload.get("intent")
                if isinstance(intent, str):
                    intent = intent.strip()
                else:
                    intent = None

                dataset_id = payload.get("dataset_id") if isinstance(payload.get("dataset_id"), str) else None

                plan_steps = payload.get("plan_steps") if isinstance(payload.get("plan_steps"), list) else None

                sql = payload.get("sql")
                sql_list: list[str] | None = None
                if isinstance(sql, list):
                    sql_list = []
                    for item in sql:
                        if isinstance(item, str) and item.strip():
                            sql_list.append(item.strip())
                        elif isinstance(item, dict):
                            candidate = item.get("query") or item.get("sql")
                            if isinstance(candidate, str) and candidate.strip():
                                sql_list.append(candidate.strip())
                elif isinstance(sql, str):
                    raw = sql.strip()
                    blocks = re.findall(r"```sql(.*?)```", raw, re.S)
                    if blocks:
                        sql_list = [b.strip() for b in blocks if b.strip()]
                    else:
                        parts = [p.strip() for p in raw.split(";")]
                        sql_list = [p + ";" for p in parts if p and p.lower().startswith(("select", "with"))]
                else:
                    sql_list = None

                comment = payload.get("comment")
                if isinstance(comment, str):
                    comment = comment.strip()
                else:
                    comment = None

                return PlannerAction(
                    action=action,
                    intent=intent,
                    sql=sql_list,
                    dataset_id=dataset_id,
                    plan_steps=plan_steps,
                    comment=comment,
                    metadata={
                        k: v for k, v in payload.items() if k not in {"action", "intent", "sql", "dataset_id", "plan_steps", "comment"}
                    },
                )
            except Exception as exc:
                print("[_parse_planner_response] JSON parse failed:", repr(exc))

        # Non-JSON: try to extract one or more SQL blocks
        blocks = re.findall(r"```sql(.*?)```", text, re.S)
        if blocks:
            stmts = [b.strip() for b in blocks if b.strip()]
            return PlannerAction(action="execute", sql=stmts, comment="SQL extracted from fenced blocks.")

        # fallback: detect plain SQL statements
        parts = [p.strip() for p in re.split(r";\s*", text) if p.strip()]
        stmts = [p + ";" for p in parts if p.lower().startswith(("select", "with"))]
        if stmts:
            return PlannerAction(action="execute", sql=stmts, comment="SQL extracted from plain text response.")

        return PlannerAction(action="analysis", comment=text)

    def _extract_json_payload(self, text: str) -> str:
        text = text.strip()

        fenced = re.search(r"```(?:json)?\s*(\{.*\})\s*```", text, re.S)
        if fenced:
            return fenced.group(1).strip()

        start = text.find("{")
        if start == -1:
            return text

        depth = 0
        in_string = False
        escape = False
        for index, char in enumerate(text[start:], start=start):
            if escape:
                escape = False
                continue
            if char == "\\":
                escape = True
                continue
            if char == '"':
                in_string = not in_string
                continue
            if in_string:
                continue
            if char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    return text[start : index + 1].strip()

        return text