from __future__ import annotations

from dataclasses import asdict
import json
import re
import unicodedata
import time
from datetime import date, datetime, time as dtime
from abc import ABC, abstractmethod
from typing import Any
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError

from .settings import AppSettings
from .contracts import PlannerAction, QueryResult, SchemaMetadata, TableMetadata


# =========================================================
# ABSTRACT
# =========================================================
class QueryPlanner(ABC):
    @abstractmethod
    def build_action(
        self,
        prompt: str,
        schema_metadata: SchemaMetadata,
        previous_queries: list[str] | None = None,
        previous_results: list[QueryResult] | None = None,
        assistant_history: list[str] | None = None,
        sample_data: list[dict] | None = None,
    ) -> PlannerAction:
        raise NotImplementedError


# =========================================================
# FALLBACK
# =========================================================
class HeuristicQueryPlanner(QueryPlanner):
    def build_action(
        self,
        prompt,
        schema_metadata,
        previous_queries=None,
        previous_results=None,
        assistant_history=None,
        sample_data=None,
    ) -> PlannerAction:
        print("[Heuristic] fallback activated")
        table = schema_metadata.tables[0].name
        return PlannerAction(
            action="execute",
            sql=[f"SELECT * FROM {table} LIMIT 10;"],
            comment="Fallback query generated by heuristic planner.",
        )


# =========================================================
# OLLAMA PLANNER
# =========================================================
class OllamaQueryPlanner(QueryPlanner):

    def __init__(self, settings: AppSettings, fallback_planner=None):
        self._settings = settings
        self._fallback = fallback_planner or HeuristicQueryPlanner()

    def build_action(
        self,
        prompt,
        schema_metadata,
        previous_queries=None,
        previous_results=None,
        assistant_history=None,
        sample_data: list[dict] | None = None,
    ) -> PlannerAction:

        print("\n================ OLLAMA PLANNER ================")
        print("[Planner] prompt:", prompt)
        print("[Planner] db:", schema_metadata.database_id)

        print("[Planner] model:", self._settings.ollama_model)
        print("[Planner] base_url:", self._settings.ollama_base_url)

        print("[Planner] previous_queries:", previous_queries)
        print("[Planner] previous_results:", len(previous_results) if previous_results else 0)
        print("[Planner] assistant_history:", assistant_history)

        t0 = time.time()

        try:
            action = self._call_ollama(
                prompt,
                schema_metadata,
                previous_queries,
                previous_results,
                assistant_history,
                sample_data,
            )
            print("[Planner] TOTAL TIME:", round(time.time() - t0, 2), "s")

            return action

        except Exception as e:
            print("\n[Planner] ERROR:", repr(e))
            print("[Planner] fallback triggered\n")
            return self._fallback.build_action(
                prompt,
                schema_metadata,
                previous_queries=previous_queries,
                previous_results=previous_results,
                assistant_history=assistant_history,
                sample_data=sample_data,
            )

    def _call_ollama(
        self,
        prompt,
        schema_metadata,
        previous_queries,
        previous_results,
        assistant_history,
        sample_data=None,
    ) -> PlannerAction:

        print("\n[Planner] CALLING OLLAMA...")

        schema_dict = asdict(schema_metadata)
        schema_str = self.simplify_schema(schema_dict)

        print("[Planner] SCHEMA SIZE:", len(schema_str))
        print("[Planner] SCHEMA:\n", schema_str)
        print("[Planner] SAMPLE DATA:", sample_data)
        print("[Planner] ASSISTANT HISTORY:", assistant_history)

        final_prompt = f"""
        You are a Data Understanding and SQL Assistant.

        Your job is to analyze the user request and the database schema. You may generate SQL queries, ask questions about the dataset, or provide analysis. Only generate SQL when you want the system to execute it.

        ---

        USER TASK:
        {prompt}

        ---

        DATABASE SCHEMA:
        {schema_str}

        ---

        DATABASE TITLE:
        {sample_data[0].get('Titulo') if sample_data and sample_data[0].get('Titulo') else 'No title provided.'}

        DATABASE DESCRIPTION:
        {sample_data[0].get('Descripción') if sample_data and sample_data[0].get('Descripción') else 'No description provided.'}

        ---

        PREVIOUS QUERIES:
        {json.dumps(previous_queries or [], ensure_ascii=False, indent=2)}

        PREVIOUS RESULTS SUMMARY:
        {json.dumps([{{'row_count': len(r.rows), 'truncated': r.truncated}} for r in (previous_results or [])], ensure_ascii=False, indent=2)}

        ASSISTANT HISTORY:
        {json.dumps(assistant_history or [], ensure_ascii=False, indent=2)}

        ---

        RESPONSE FORMAT:
        Return a JSON object only. The JSON object must include:
        - action: "execute", "analysis", or "final"
        - sql: the SQL query to execute when action == "execute"
        - comment: a short explanation of the plan or analysis

        Example responses:
        {{"action":"execute","sql":["SELECT * FROM customers LIMIT 10;"],"comment":"Explorar las filas iniciales."}}
        {{"action":"analysis","comment":"La tabla customers tiene un campo id UUID; deberíamos revisar si hay duplicados."}}
        {{"action":"final","comment":"El dataset es adecuado para análisis de clientes básicos."}}

        RULES:
        1. When you want to run a query, set action to "execute" and provide valid SQL.
        2. Do not execute SQL in your head. Only use SQL in the sql field.
        3. If you only want to reason or ask a question about the dataset, set action to "analysis".
        4. When you are done and want to finish the reasoning, set action to "final".
        5. Do not mix SQL and analysis outside the designated JSON fields.
        6. If you return a SQL query, it should be a single statement.
        7. Use only the schema and available results; do not invent tables.
        """

        print("\n[Planner] FINAL PROMPT SIZE:", len(final_prompt))
        print("[Planner] --- PROMPT START ---")
        print(final_prompt[:500], "...")
        print("[Planner] --- PROMPT END ---")

        payload = json.dumps({
            "model": self._settings.ollama_model,
            "prompt": final_prompt,
            "stream": False,
        }).encode()

        print("\n[Planner] sending request to Ollama...")

        req = Request(
            f"{self._settings.ollama_base_url}/api/generate",
            data=payload,
            headers={"Content-Type": "application/json"},
        )

        start = time.time()

        try:
            with urlopen(req, timeout=self._settings.ollama_timeout_seconds) as r:
                print("[Planner] waiting response from Ollama...")
                raw = r.read().decode()

            print("[Planner] RAW RESPONSE SIZE:", len(raw))
            print("[Planner] RAW RESPONSE:", raw[:300])

            parsed = json.loads(raw)
            response = parsed.get("response", "").strip()

            print("[Planner] MODEL RESPONSE:", response)
            print("[Planner] OLLAMA TIME:", round(time.time() - start, 2), "s")

            # Try to parse response; if invalid, do a short re-ask loop
            max_reasks = 2
            parsed_action = self._parse_planner_response(response)
            if parsed_action.action in {"execute", "analysis", "final"} and (
                parsed_action.action != "execute" or parsed_action.sql
            ):
                return parsed_action

            # re-ask attempts
            for retry in range(max_reasks):
                rem_prompt = (
                    final_prompt
                    + "\n\nThe previous model response was not valid or did not follow the required JSON schema."
                    + " Please respond ONLY with a JSON object matching the format exactly."
                    + " Example: {\"action\":\"execute\",\"sql\":[\"SELECT * FROM customers LIMIT 10;\"],\"comment\":\"Explorar\"}"
                )

                payload = json.dumps({
                    "model": self._settings.ollama_model,
                    "prompt": rem_prompt,
                    "stream": False,
                }).encode()

                req = Request(
                    f"{self._settings.ollama_base_url}/api/generate",
                    data=payload,
                    headers={"Content-Type": "application/json"},
                )

                with urlopen(req, timeout=self._settings.ollama_timeout_seconds) as r:
                    raw2 = r.read().decode()

                parsed2 = json.loads(raw2)
                response2 = parsed2.get("response", "").strip()
                print(f"[Planner] Re-ask attempt {retry+1}, MODEL RESPONSE:", response2)
                parsed_action = self._parse_planner_response(response2)
                if parsed_action.action in {"execute", "analysis", "final"} and (
                    parsed_action.action != "execute" or parsed_action.sql
                ):
                    return parsed_action

            # If still invalid, return the last parse (as analysis)
            return parsed_action

        except (URLError, HTTPError, TimeoutError) as e:
            print("\n[Planner] OLLAMA ERROR:", repr(e))
            raise

    def simplify_schema(self, schema: dict) -> str:
        lines = []

        lines.append(f"DATABASE: {schema.get('database_id')}")
        lines.append(f"DIALECT: {schema.get('dialect')}")
        lines.append("")

        for table in schema.get("tables", []):
            lines.append(f"TABLE: {table.get('name')}")
            lines.append("")
            lines.append("COLUMNS:")

            for col in table.get("columns", []):
                name = col.get("name")
                col_type = col.get("type")

                flags = []

                if col.get("is_primary_key"):
                    flags.append("PK")

                if col.get("is_foreign_key"):
                    flags.append("FK")

                flag_str = f" [{', '.join(flags)}]" if flags else ""

                lines.append(f"- {name} ({col_type}){flag_str}")

            lines.append("")

            pk = table.get("primary_key", [])
            lines.append(f"PRIMARY KEY: {pk if pk else 'none'}")

            # relations (si existen)
            relations = table.get("relations", [])
            if relations:
                lines.append(f"RELATIONS: {relations}")
            else:
                lines.append("RELATIONS: none")

            lines.append(f"TOTAL COLUMNS: {len(table.get('columns', []))}")

        return "\n".join(lines)


    def _extract_sql(self, text: str) -> str:

        print("\n[_extract_sql] input:", text)

        text = text.strip()

        # 1. Detectar si es SQL con bloque de código
        match = re.search(r"```sql(.*?)```", text, re.S)
        if match:
            print("[_extract_sql] fenced SQL detected")
            sql = match.group(1).strip()
            if sql.lower().startswith(("select", "with")):
                return sql + ";"
            # Si el bloque SQL no empieza con SELECT/WITH, tratarlo como texto
            return sql

        # 2. Detectar si es SQL plano (sin bloques)
        if text.lower().startswith(("select", "with")):
            print("[_extract_sql] plain SQL detected")
            return text + ";"

        # 3. Detectar si es JSON (dataset evaluation)
        if text.startswith("{") and text.endswith("}"):
            print("[_extract_sql] JSON response detected, returning as-is")
            try:
                # Validar que sea JSON válido
                json.loads(text)
                return text
            except json.JSONDecodeError:
                print("[_extract_sql] invalid JSON, treating as plain text")
                return text

        # 4. Cualquier otra respuesta (texto plano, evaluación, etc.)
        print("[_extract_sql] plain text response, returning as-is")
        return text

    def _parse_planner_response(self, text: str) -> PlannerAction:

        print("[_parse_planner_response] input:", text)

        text = text.strip()

        if text.startswith("{") and text.endswith("}"):
            try:
                payload = json.loads(text)
                action = payload.get("action")
                if action not in {"execute", "analysis", "final"}:
                    raise ValueError(f"Invalid action: {action}")

                sql = payload.get("sql")
                # Normalize sql into a list of statements
                sql_list: list[str] | None = None
                if isinstance(sql, list):
                    sql_list = [s.strip() for s in sql if isinstance(s, str) and s.strip()]
                elif isinstance(sql, str):
                    raw = sql.strip()
                    # try to extract fenced SQL blocks
                    blocks = re.findall(r"```sql(.*?)```", raw, re.S)
                    if blocks:
                        sql_list = [b.strip() for b in blocks if b.strip()]
                    else:
                        # split by semicolon and keep statements that look like queries
                        parts = [p.strip() for p in raw.split(";")]
                        sql_list = [p + ";" for p in parts if p and p.lower().startswith(("select", "with"))]
                else:
                    sql_list = None

                comment = payload.get("comment")
                if isinstance(comment, str):
                    comment = comment.strip()
                else:
                    comment = None

                return PlannerAction(
                    action=action,
                    sql=sql_list,
                    comment=comment,
                    metadata={k: v for k, v in payload.items() if k not in {"action", "sql", "comment"}},
                )
            except Exception as exc:
                print("[_parse_planner_response] JSON parse failed:", repr(exc))

        # Non-JSON: try to extract one or more SQL blocks
        blocks = re.findall(r"```sql(.*?)```", text, re.S)
        if blocks:
            stmts = [b.strip() for b in blocks if b.strip()]
            return PlannerAction(action="execute", sql=stmts, comment="SQL extracted from fenced blocks.")

        # fallback: detect plain SQL statements
        parts = [p.strip() for p in re.split(r";\s*", text) if p.strip()]
        stmts = [p + ";" for p in parts if p.lower().startswith(("select", "with"))]
        if stmts:
            return PlannerAction(action="execute", sql=stmts, comment="SQL extracted from plain text response.")

        return PlannerAction(action="analysis", comment=text)